### ISSUE TITLE
non-joint BPE and number of BPE operations

### ISSUE THREAD

**Issue by vmando** [rsennrich/wmt16-scripts#3]
Hi,

how should one handle the case of different alphabets between source and target language, for instance English to an Asian language?

Should one replace this line in the `preprocess.sh` script

```
# train BPE
cat data/corpus.tc.$SRC data/corpus.tc.$TRG | $subword_nmt/learn_bpe.py -s $bpe_operations > model/$SRC$TRG.bpe
```

with two separate lines

```
cat data/corpus.tc.$SRC | $subword_nmt/learn_bpe.py -s $bpe_operations > model/$SRC.bpe
cat data/corpus.tc.$TRG | $subword_nmt/learn_bpe.py -s $bpe_operations > model/$TRG.bpe
```

?

Moreover, what about the `$bpe_operations` value? Actually, I don't understand how the following comment in the `preprocess.sh` file :

```
# number of merge operations. Network vocabulary should be slightly larger (to include characters),
# or smaller if the operations are learned on the joint vocabulary
bpe_operations=89500
```

relates to the 

`VOCAB_SIZE=90000`

line in the `config.py` file.  Since in `preprocess.sh` the BPE is learned on the joint vocabulary (right?), I would expect `VOCAB_SIZE` to be slightly smaller than 89500, not larger. Could you please explain?

Thanks,
Vito

**Comment by rsennrich** [comment]
to your first question: yes, that's what I would recommend for non-joint BPE (of course, the lines with apply_bpe.py need to be adjusted accordingly)

to your second question: for non-joint BPE, the total vocabulary size is the number of BPE operations plus the initial character vocabulary, so the network vocabulary should be slightly larger. For joint BPE, the actual vocabulary can be smaller because of units that only occur in one of the two languages. Personally, I sometimes adjust the network vocabulary size based on the output of build_dictionary.py .

**Comment by vmando** [comment]
Got it, thank you
